# Generated by Django 6.0.7 on 2026-07-15 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='aaf989ae', unique=True),
        ),
    ]
