# Generated by Django 6.0.7 on 2026-07-15 06:28

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890abcdef', editable=False, length=8, max_length=25, prefix='', unique=True),
        ),
    ]
