# Generated by Django 6.0.7 on 2026-07-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pick_up_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
