# Generated by Django 6.0.7 on 2026-07-27 21:29

import django.db.models.deletion
import django.utils.timezone
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_pick_up_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890abcdef', editable=False, length=8, max_length=25, prefix='', unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tier', models.CharField(choices=[('REGULAR', 'Regular'), ('VIP', 'VIP')], default='REGULAR', max_length=20)),
                ('combo_description', models.TextField(help_text='Food/drink included with this ticket, e.g. 1 bun + 1 small coffee')),
                ('is_purchasable', models.BooleanField(default=True, help_text='Uncheck for reward-only tickets (e.g. VIP referral reward).')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('slug', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890abcdef', editable=False, length=8, max_length=25, prefix='', unique=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='store.event')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='EventOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('referred_by_code', models.CharField(blank=True, help_text='Referral code of the user who referred this buyer.', max_length=10, null=True)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Processing', 'Processing'), ('Failed', 'Failed')], default='Processing', max_length=100)),
                ('payment_method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Flutterwave', 'Flutterwave')], default=None, max_length=100, null=True)),
                ('order_status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Delivered', 'Delivered')], default='Pending', max_length=100)),
                ('order_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=25, prefix='')),
                ('payment_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_free_reward', models.BooleanField(default=False, help_text='True when this order was granted as a referral reward.')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_orders', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.event')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='store.eventticket')),
            ],
            options={
                'verbose_name_plural': 'Event Orders',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ReferralReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('TWO', 'Bring 2 — 1 regular ticket free'), ('FIVE', 'Bring 5 — 1 regular ticket + 1 shawarma'), ('TEN', 'Bring 10+ — 1 VIP ticket + 1 shawarma')], max_length=10)),
                ('referral_count', models.PositiveIntegerField(default=0)),
                ('reward_description', models.CharField(max_length=255)),
                ('includes_shawarma', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Fulfilled', 'Fulfilled')], default='Pending', max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_rewards', to='store.event')),
                ('free_ticket_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_reward_source', to='store.eventorder')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('referrer', 'event', 'tier')},
            },
        ),
    ]
