# Generated by Django 6.0.7 on 2026-07-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_event_eventticket_eventorder_referralreward'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventticket',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_tickets/'),
        ),
        migrations.AddField(
            model_name='eventticket',
            name='image_static',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
