# Generated by Django 6.0.7 on 2026-09-18 08:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_eventticket_image_eventticket_image_static"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkshopRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parent_name",
                    models.CharField(
                        max_length=150, verbose_name="Parent/Guardian name"
                    ),
                ),
                (
                    "parent_phone",
                    models.CharField(
                        max_length=30, verbose_name="Parent/Guardian phone"
                    ),
                ),
                (
                    "parent_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Parent/Guardian email"
                    ),
                ),
                ("student_name", models.CharField(max_length=150)),
                ("student_age", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "pricing_tier",
                    models.CharField(
                        choices=[
                            ("WORKSHOP_DAY", "Workshop-day price"),
                            ("REGULAR", "Regular price"),
                        ],
                        default="WORKSHOP_DAY",
                        max_length=20,
                    ),
                ),
                (
                    "interested_in_fellowship",
                    models.BooleanField(
                        default=False,
                        help_text="Interested in the 1-year Fellowship pathway.",
                    ),
                ),
                (
                    "school_code",
                    models.CharField(
                        blank=True,
                        help_text="Code shared by the participant's school, e.g. FSS-SCHOOL01.",
                        max_length=30,
                        verbose_name="School / Referral code",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("Paid", "Paid"),
                            ("Processing", "Processing"),
                            ("Failed", "Failed"),
                        ],
                        default="Processing",
                        max_length=100,
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.AddField(
            model_name="eventorder",
            name="attendee_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="eventorder",
            name="attendee_phone",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
