# Generated by Django 6.0.7 on 2026-09-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0014_seed_osisioma_relaunch"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("school_name", models.CharField(blank=True, max_length=150)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
    ]
