# Generated by Django 6.0.7 on 2026-09-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0016_seed_school_codes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventticket",
            name="tier",
            field=models.CharField(
                choices=[
                    ("REGULAR", "Regular"),
                    ("VIP", "VIP"),
                    ("EXPLORER", "Explorer"),
                    ("COMMUNITY", "Community"),
                    ("CREATOR", "Creator"),
                    ("VVIP", "VVIP"),
                ],
                default="REGULAR",
                max_length=20,
            ),
        ),
    ]
