# Generated by Django 6.0.7 on 2026-07-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_team_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='played',
            field=models.BooleanField(default=False),
        ),
    ]
