# Generated by Django 6.0.7 on 2026-09-18 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_match_played"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountrySlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("capacity", models.PositiveIntegerField(default=1)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to manually close this country even if capacity remains.",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="team",
            name="country",
            field=models.ForeignKey(
                blank=True,
                help_text="Country this team represents in the Cantaball World Cup.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teams",
                to="app.countryslot",
            ),
        ),
    ]
