# Generated by Django 6.0.7 on 2026-07-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PLAYER', 'Player'), ('ADMIN', 'Admin')], default='PLAYER', max_length=50),
        ),
    ]
