# Generated by Django 6.0.7 on 2026-07-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_user_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_marketing',
            field=models.BooleanField(default=False),
        ),
    ]
