# Generated by Django 6.0.7 on 2026-07-28 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_user_is_marketing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_marketing',
            new_name='is_marketer',
        ),
    ]
